# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af228501eec1d5c859c1fbcc66d72419820a42f8c1a0f7d2ef58f022c6147fff263954df3e4eeb21b349253594e461c7ea9a42e83f321fc3dd2efe2ac76fb52c

test:
  secret_key_base: 249810b527bbde01caa4fa9b6941a65c7979e0ee143c3183860aad70999420e44f9480a715da659983c4d5d16628a3059c99be69fbd0bb02cac47379a54ff1ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
